"""TRIZ Bloom Lab — compact educational knowledge base.

The contradiction matrix below intentionally contains a curated set of high-frequency
cells for an MVP. Pairs not found in the curated table are handled by a transparent,
category-based fallback in triz_engine.py.
"""

PARAMETERS = {
    1: "Hareketli nesnenin ağırlığı",
    2: "Hareketsiz nesnenin ağırlığı",
    3: "Hareketli nesnenin uzunluğu",
    4: "Hareketsiz nesnenin uzunluğu",
    5: "Hareketli nesnenin alanı",
    6: "Hareketsiz nesnenin alanı",
    7: "Hareketli nesnenin hacmi",
    8: "Hareketsiz nesnenin hacmi",
    9: "Hız",
    10: "Kuvvet",
    11: "Gerilme veya basınç",
    12: "Şekil",
    13: "Nesnenin bileşim kararlılığı",
    14: "Dayanım",
    15: "Hareketli nesnenin etki süresi",
    16: "Hareketsiz nesnenin etki süresi",
    17: "Sıcaklık",
    18: "Aydınlatma şiddeti",
    19: "Hareketli nesnenin enerji kullanımı",
    20: "Hareketsiz nesnenin enerji kullanımı",
    21: "Güç",
    22: "Enerji kaybı",
    23: "Madde kaybı",
    24: "Bilgi kaybı",
    25: "Zaman kaybı",
    26: "Madde miktarı",
    27: "Güvenilirlik",
    28: "Ölçüm doğruluğu",
    29: "Üretim hassasiyeti",
    30: "Nesneye etki eden zararlı faktörler",
    31: "Zararlı yan etkiler",
    32: "Üretilebilirlik",
    33: "Kullanım kolaylığı",
    34: "Onarılabilirlik",
    35: "Uyarlanabilirlik veya çok yönlülük",
    36: "Sistem/cihaz karmaşıklığı",
    37: "Tespit ve ölçme güçlüğü",
    38: "Otomasyon düzeyi",
    39: "Üretkenlik",
}

PRINCIPLES = {
    1: ("Segmentasyon", "Sistemi bağımsız, modüler veya yerel parçalara ayır."),
    2: ("Ayırma", "Sorun yaratan kısmı sistemden ayır veya yalnızca gerekli kısmı koru."),
    3: ("Yerel kalite", "Her parçayı aynı yapmak yerine yerel koşula göre özelleştir."),
    4: ("Asimetri", "Simetrik yapıyı bozarak işlevsel bir farklılık yarat."),
    5: ("Birleştirme", "Benzer işlemleri, nesneleri veya zamanları bir araya getir."),
    6: ("Evrensellik", "Bir öğenin birden fazla işlev görmesini sağla."),
    7: ("İç içe geçirme", "Bir nesneyi başka bir nesnenin içine veya katmanına yerleştir."),
    8: ("Karşı ağırlık", "Olumsuz etkiyi dengeleyen karşıt bir etki kullan."),
    9: ("Ön karşı etki", "Beklenen zararlı etki ortaya çıkmadan önce ters yönde hazırlık yap."),
    10: ("Önceden eylem", "Gerekli işlemin tamamını veya kritik bölümünü önceden gerçekleştir."),
    11: ("Önceden yastıklama", "Arıza veya risk için koruyucu önlem ya da yedek mekanizma hazırla."),
    12: ("Eş potansiyellik", "Gereksiz yükselme, düşme veya dönüşümü ortadan kaldır."),
    13: ("Tersine çevirme", "İşlemin yönünü, sırasını, aktif-pasif rolünü veya kontrol mantığını tersine çevir."),
    14: ("Eğrilik", "Doğrusal/geometrik yapıyı eğrisel, döner veya küresel yapıya dönüştür."),
    15: ("Dinamiklik", "Sistemin özelliklerini koşullara göre değişebilir ve uyarlanabilir yap."),
    16: ("Kısmi veya aşırı eylem", "Tam sonuç zor ise daha azını veya kontrollü fazlasını uygula."),
    17: ("Başka boyut", "Tek düzlem yerine yeni bir boyut, katman veya kanal kullan."),
    18: ("Mekanik titreşim", "Titreşim, salınım veya darbeli hareketten yararlan."),
    19: ("Periyodik eylem", "Sürekli işlem yerine periyodik, darbeli veya zamanlanmış işlem uygula."),
    20: ("Yararlı eylemin sürekliliği", "Boş beklemeleri azalt; yararlı faaliyeti kesintisiz sürdür."),
    21: ("Hızla geçme", "Zararlı veya riskli aşamadan çok hızlı geç."),
    22: ("Zararı yarara çevirme", "Zararlı etkiyi başka bir yararlı işlev için kullan."),
    23: ("Geri bildirim", "Çıktıyı ölçerek sistemi dinamik biçimde düzelt."),
    24: ("Aracı kullanma", "Doğrudan etkileşim yerine geçici veya kalıcı bir aracı unsur kullan."),
    25: ("Kendi kendine hizmet", "Sistemin bakım, ayar veya artıklarını kendi işleviyle yönetmesini sağla."),
    26: ("Kopyalama", "Pahalı/riskli nesne yerine model, simülasyon veya temsil kullan."),
    27: ("Ucuz kısa ömürlü nesneler", "Tek pahalı çözüm yerine değiştirilebilir düşük maliyetli öğeler kullan."),
    28: ("Mekanik sistemin yerine koyma", "Mekanik çözümü optik, elektriksel, manyetik, akustik veya dijital çözümle değiştir."),
    29: ("Pnömatik ve hidrolik", "Katı parçalar yerine gaz veya sıvı davranışından yararlan."),
    30: ("Esnek kabuklar ve ince filmler", "Ağır/rijit yapıları esnek yüzeylerle değiştir."),
    31: ("Gözenekli malzemeler", "Gözenekli yapı veya boşluklardan yararlan."),
    32: ("Renk değişimi", "Durumu renk, optik özellik veya görünür işaretle belirt."),
    33: ("Homojenlik", "Etkileşen öğeleri benzer özellikte veya uyumlu malzemede seç."),
    34: ("Atma ve yeniden kazanma", "İşlevi biten parçayı kaldır; gerekirse yeniden oluştur veya geri kazan."),
    35: ("Parametre değişikliği", "Boyut, yoğunluk, esneklik, süre, ayrıntı düzeyi gibi parametreleri değiştir."),
    36: ("Faz geçişi", "Faz değişiminin hacim, enerji veya davranış etkilerinden yararlan."),
    37: ("Isıl genleşme", "Sıcaklığa bağlı genleşme/daralmayı işlevsel olarak kullan."),
    38: ("Güçlü oksitleyiciler", "Tepkimeyi hızlandırmak için ortamın kimyasal etkinliğini artır."),
    39: ("Atıl ortam", "İstenmeyen tepkimeyi azaltmak için nötr veya kontrollü ortam kullan."),
    40: ("Kompozit malzemeler", "Tek tip yapı yerine farklı özellikleri birleştiren kompozit kullan."),
}

# Curated high-frequency contradiction cells. Key = (improving, worsening).
CONTRADICTION_CELLS = {
    (27, 36): [13, 35, 1],
    (27, 25): [10, 23, 35, 1],
    (27, 39): [1, 10, 11, 35],
    (28, 36): [6, 32, 13, 24],
    (28, 25): [10, 19, 23, 32],
    (29, 36): [1, 26, 27, 35],
    (35, 36): [15, 29, 37, 28],
    (35, 25): [15, 10, 19, 35],
    (38, 36): [5, 12, 26, 35],
    (38, 27): [28, 26, 23, 35],
    (39, 36): [1, 10, 28, 35],
    (39, 25): [10, 20, 21, 35],
    (34, 36): [1, 11, 25, 35],
    (33, 36): [6, 15, 23, 32],
    (14, 1): [1, 8, 15, 40],
    (14, 2): [1, 8, 15, 40],
    (14, 25): [10, 18, 28, 40],
    (9, 27): [10, 19, 20, 23],
    (9, 36): [10, 15, 28, 35],
    (25, 27): [10, 11, 20, 23],
    (25, 36): [1, 10, 19, 35],
    (21, 22): [19, 20, 23, 35],
    (21, 36): [6, 15, 28, 35],
    (24, 36): [1, 23, 26, 35],
    (24, 25): [10, 19, 23, 26],
    (30, 27): [11, 22, 23, 39],
    (31, 27): [2, 11, 22, 39],
    (32, 36): [1, 6, 26, 35],
    (17, 27): [10, 11, 35, 39],
    (10, 1): [1, 8, 15, 40],
    (10, 36): [6, 13, 28, 35],
}

# Category profiles used by the transparent fallback recommender.
PARAMETER_CATEGORIES = {
    "performans": {9, 10, 14, 21, 27, 28, 29, 39},
    "zaman": {15, 16, 25},
    "enerji": {17, 19, 20, 21, 22},
    "bilgi": {24, 28, 37, 38},
    "uyum": {33, 34, 35, 36},
    "risk": {13, 27, 30, 31},
    "boyut": {1, 2, 3, 4, 5, 6, 7, 8, 12, 26},
}

FALLBACK_BY_CATEGORY = {
    ("performans", "uyum"): [1, 15, 23, 35],
    ("performans", "zaman"): [10, 19, 20, 21],
    ("performans", "enerji"): [19, 20, 23, 35],
    ("performans", "risk"): [9, 11, 23, 35],
    ("performans", "boyut"): [1, 8, 15, 40],
    ("bilgi", "uyum"): [1, 23, 26, 35],
    ("bilgi", "zaman"): [10, 19, 23, 26],
    ("uyum", "zaman"): [1, 10, 15, 35],
    ("uyum", "risk"): [11, 15, 23, 35],
    ("zaman", "risk"): [10, 11, 20, 23],
    ("enerji", "uyum"): [6, 15, 28, 35],
    ("boyut", "performans"): [1, 7, 15, 40],
}

SECTORS = [
    "Afet ve acil durum",
    "Yazılım / karar destek",
    "Üretim",
    "Lojistik ve tedarik zinciri",
    "Sağlık",
    "Enerji",
    "Telekomünikasyon",
    "Eğitim",
    "Diğer",
]

DESIGN_AROUND_STRATEGIES = {
    "İşlevi böl ve dağıt": [1, 3, 24],
    "Kontrol yönünü tersine çevir": [13, 23, 25],
    "Sabit yapıyı dinamik yap": [15, 19, 35],
    "Fiziksel yöntemi başka alanla değiştir": [28, 26, 32],
    "Doğrudan etkileşim yerine aracı kullan": [24, 5, 6],
    "Önceden hazırlık + yerel güncelleme": [10, 1, 23],
}
